# fly.toml app configuration file generated for agentic-graysky on 2025-03-25T08:47:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agentic-graysky'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PRIMARY_REGION = "syd"
  LITEFS_DB_PATH = "/var/lib/litefs/data/graysky.db"
  LITEFS_MOUNTED = "true"
  FLY_APP_NAME = "agentic-graysky"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

# Enable consul for primary election
[experimental]
  enable_consul = true

# This enables the LiteFS HTTP server for connecting to other instances
[[services]]
  protocol = "tcp"
  internal_port = 20202
  processes = ["app"]
  
  [[services.ports]]
    port = 20202
    handlers = ["http"]

[[metrics]]
  port = 9091
  path = "/metrics"
